const express = require('express')
const router = express.Router()
const fs = require('fs')

const { cekKey, checkLimit } = require('../database/db')
const { getFile } = require('../lib/function')
const { cekUsername, cekRequest, cekEmail } = require('../database/premium')
const { tiktok, tiktok2, tiktoknowm, youtube, twitter, twitter2, zippyshare, xnxxdl, xnxxsearch, pindl, mediafire, soundcloud, instagram, instagram2, instagram3, instastory, sfiledl, anonfiledl, stickerDl, telesticker, facebook, aiovideodl, pixiv, spotifydl } = require('../features/downloader')
const { pinterest, sticker, pixivsearch, happymod, sfilesearch, konachan, alphacoders, wallpapercave, domainsearch, cekdomain, steleSearch, stickerline, gimage, ytsearch, google, tiktoksearch, xsearch, instagramsearch, facebooksearch, threadssearch, redditsearch, telegramsearch, linkedinsearch, wiki, spotifysearch  } = require('../features/searching')
const { husbu, loli, milf, cosplay, randomimage, waifu, neko, shinobu, megumin, bully, cuddle, cry, hug, awoo, kiss, lick, slap } = require('../features/randomimage')
const { nh, nhpdf, nhsearch, nhpopular, nhlatest, nhrandom, doujindesu, doujinsearch, doujinlatest, komiklatest, komikdl, mynimesearch, mynimelatest, hanimelatest, animeinfo, kusonime, storyanime, nekopoi, nekopoiLatest } = require('../features/animanga')
const { melolohome, melolodetail, melolosearch, melologuides, meloloranking, melolocategory, melolodownload, melolodownloadfile } = require('../features/melolo')
const { ghstalk, igstalk, wattpad, npminfo } = require('../features/stalking')
const { emailvalidate, jsonvalidate, base64encode, base64decode, jsconfuser } = require('../features/tools')
const { tebakgambar, asahotak, susunkata, siapakahaku, tebakkata, tebakkalimat, tebaktebakan, tekateki, tebakbendera, tebakkimia, caklontong, tebaklirik, family100, tebakkabupaten, truthdare } = require('../features/entertainment')
const { artinama, artimimpi, ramaljodoh, nomorhoki, zodiak, kecocokan_nama, kecocokan_nama_pasangan, tanggal_jadian_pernikahan, sifat_usaha_bisnis, rejeki_hoki_weton, pekerjaan_weton_lahir, ramalan_nasib, cek_potensi_penyakit, arti_kartu_tarot, petung_hari_baik, hari_sangar_taliwangke, primbon_hari_naas, rahasia_naga_hari, primbon_arah_rejeki, ramalan_peruntungan, weton_jawa, sifat_karakter_tanggal_lahir, potensi_keberuntungan, primbon_memancing_ikan, seberapagay } = require('../features/primbon')
const { ppcouple, wangy, wangy2, nenen, simp, sherk, quotes, quotesnime, gi, giwp, herodetail, herolist } = require('../features/other')
const { ling26, nemotron3super120b, gptoss120b, glm45air, nemotron3nano30b, nemotronnano12bvl, qwen3coder, llamaNemotronEmbedVl } = require('../features/ai')

let creatorFeatures = null
if (process.env.VERCEL) {
    console.warn('[WARN] Creator features disabled on Vercel to reduce function bundle size')
} else {
    try {
        const runtimeRequire = eval('require')
        creatorFeatures = runtimeRequire('../features/creator')
    } catch (error) {
        console.warn('[WARN] Creator features disabled:', error.message)
    }
}

     router.get('/checkapikey', async (req, res) => {
         let apikey = req.query.apikey
         if (!apikey) return res.status(400).send({ status: 400, message: 'apikey parameter cannot be empty', result: 'error' })
         let check = await cekKey(apikey)
         if (!check) return res.status(404).send({ status: 404, message: `apikey ${apikey} not found, please register first.` })
         let limit = await checkLimit(apikey)
         let username = await cekUsername(apikey)
         let request = await cekRequest(apikey)
         let email = await cekEmail(apikey)
         res.status(200).send({ status: 200, message: 'succes', result: { username: username, request: request, email: email, limit: limit }})
     })
     
     router.get('/toFile', async(req, res) => {
         let url = req.query.url 
         const buffer = await getFile(url)
         fs.writeFileSync(__path+ `/tmp/temp.${buffer.ext}`, buffer.data)
         res.sendFile(__path+ `/tmp/temp.${buffer.ext}`)
     })
     
     // Downloader
     router.get('/tiktok', tiktok)
     router.get('/tiktok2', tiktok2)
     router.get('/tiktoknowm', tiktoknowm)
     router.get('/youtube', youtube)
     router.get('/twitter', twitter)
     router.get('/twitter2', twitter2)
     router.get('/zippyshare', zippyshare)
     router.get('/xnxxdl', xnxxdl)
     router.get('/xnxxsearch', xnxxsearch)
     router.get('/pindl', pindl)
     router.get('/mediafire', mediafire)
     router.get('/scdl', soundcloud)
     router.get('/igdl', instagram)
     router.get('/igdl2', instagram2)
     router.get('/igdl3', instagram3)
     router.get('/igstory', instastory)
     router.get('/sfiledl', sfiledl)
     router.get('/anonfiledl', anonfiledl)
     router.get('/stickerdl', stickerDl)
     router.get('/telesticker', telesticker)
     router.get('/fbdl', facebook)
     router.get('/aiovideodl', aiovideodl)
     router.get('/pixiv', pixiv)
     router.get('/spotifydl', spotifydl)
     
     // Searching
     router.get('/pinterest', pinterest)
     router.get('/sticker', sticker)
     router.get('/pixivsearch', pixivsearch)
     router.get('/happymod', happymod)
     router.get('/sfilesearch', sfilesearch)
     router.get('/konachan', konachan)
     router.get('/alphacoders', alphacoders)
     router.get('/wallpapercave', wallpapercave)
     router.get('/domainsearch', domainsearch)
     router.get('/cekdomain', cekdomain)
     router.get('/stelesearch', steleSearch)
     router.get('/stickerline', stickerline)
     router.get('/gimage', gimage)
     router.get('/ytsearch', ytsearch)
     router.get('/google', google)
     router.get('/tiktoksearch', tiktoksearch)
     router.get('/xsearch', xsearch)
     router.get('/instagramsearch', instagramsearch)
     router.get('/facebooksearch', facebooksearch)
     router.get('/threadssearch', threadssearch)
     router.get('/redditsearch', redditsearch)
     router.get('/telegramsearch', telegramsearch)
     router.get('/linkedinsearch', linkedinsearch)
     router.get('/wikipedia', wiki)
     router.get('/spotifysearch', spotifysearch)

     // Tools
     router.get('/emailvalidate', emailvalidate)
     router.get('/jsonvalidate', jsonvalidate)
     router.get('/base64encode', base64encode)
     router.get('/base64decode', base64decode)
     router.get('/jsconfuser', jsconfuser)
     
     //Random Image
     router.get('/randomimage/waifu', waifu)
     router.get('/randomimage/husbu', husbu)
     router.get('/randomimage/loli', loli)
     router.get('/randomimage/milf', milf)
     router.get('/randomimage/cosplay', cosplay)
     router.get('/randomimage', randomimage)
     router.get('/randomimage/neko', neko)
     router.get('/randomimage/shinobu', shinobu)
     router.get('/randomimage/megumin', megumin)
     router.get('/randomimage/bully', bully)
     router.get('/randomimage/cuddle', cuddle)
     router.get('/randomimage/cry', cry)
     router.get('/randomimage/hug', hug)
     router.get('/randomimage/awoo', awoo)
     router.get('/randomimage/kiss', kiss)
     router.get('/randomimage/lick', lick)
     router.get('/randomimage/slap', slap)
     
     // Animanga
     router.get('/nhentai', nh)
     router.get('/nhentaipdf', nhpdf)
     router.get('/nhsearch', nhsearch)
     router.get('/nhpopular', nhpopular)
     router.get('/nhlatest', nhlatest)
     router.get('/nhrandom', nhrandom)
     router.get('/doujindesu', doujindesu)
     router.get('/doudesusearch', doujinsearch)
     router.get('/doudesulatest', doujinlatest)
     router.get('/komiklatest', komiklatest)
     router.get('/komikdl', komikdl)
     router.get('/mynimekusearch', mynimesearch)
     router.get('/animeinfo', animeinfo)
     router.get('/mynimekulatest', mynimelatest)
     router.get('/hanimelatest', hanimelatest)
     router.get('/kusonime', kusonime)
     router.get('/storyanime', storyanime)
     router.get('/nekopoi', nekopoi)
     router.get('/nekopoilatest', nekopoiLatest)

     // Melolo
     router.get('/melolohome', melolohome)
     router.get('/melolodetail', melolodetail)
     router.get('/melolosearch', melolosearch)
     router.get('/melolodownload', melolodownload)
     router.get('/melolodownloadfile', melolodownloadfile)
     router.get('/melologuides', melologuides)
     router.get('/meloloranking', meloloranking)
     router.get('/melolocategory', melolocategory)
     
     // Stalking
     router.get('/stalkgithub', ghstalk)
     router.get('/stalkwattpad', wattpad)
     router.get('/stalkig', igstalk)
     router.get('/stalknpm', npminfo)
     
     if (creatorFeatures) {
         const { welcome, welcome2, goodbye, goodbye2, promote, demote, rankcard, levelup, gfx, gfx2, gfx3, gfx4, gfx5, gura, burn, spongebob, patrick, xnxx, hornycard, jojo, bonk, ship, removebeg, komunis, wasted, wanted, changemymind, notstonk, stonk, rip, gay, lisa, discord, trash, deletes, trigger, blur, circle } = creatorFeatures

         // Creator
         router.get('/welcome', welcome)
         router.get('/welcome2', welcome2)
         router.get('/goodbye', goodbye)
         router.get('/goodbye2', goodbye2)
         router.get('/promote', promote)
         router.get('/demote', demote)
         router.get('/rankcard', rankcard)
         router.get('/levelup', levelup)
         router.get('/gfx', gfx)
         router.get('/gfx2', gfx2)
         router.get('/gfx3', gfx3)
         router.get('/gfx4', gfx4)
         router.get('/gfx5', gfx5)
         router.get('/gura', gura)
         router.get('/burn', burn)
         router.get('/spongebob', spongebob)
         router.get('/patrick', patrick)
         router.get('/hornycard', hornycard)
         router.get('/xnxx', xnxx)
         router.get('/jojo', jojo)
         router.get('/bonk', bonk)
         router.get('/ship', ship)
         router.get('/removebg', removebeg)
         router.get('/komunis', komunis)
         router.get('/wasted', wasted)
         router.get('/wanted', wanted)
         router.get('/changemymind', changemymind)
         router.get('/notstonk', notstonk)
         router.get('/stonk', stonk)
         router.get('/rip', rip)
         router.get('/gay', gay)
         router.get('/lisa', lisa)
         router.get('/discord', discord)
         router.get('/trash', trash)
         router.get('/delete', deletes)
         router.get('/triggered', trigger)
         router.get('/blur', blur)
         router.get('/circle', circle)
     }
     
     // Entertainment
     router.get('/tebakgambar', tebakgambar)
     router.get('/asahotak', asahotak)
     router.get('/siapakahaku', siapakahaku)
     router.get('/susunkata', susunkata)
     router.get('/tebakkata', tebakkata)
     router.get('/tebakkalimat', tebakkalimat)
     router.get('/tebaktebakan', tebaktebakan)
     router.get('/tekateki', tekateki)
     router.get('/tebakbendera', tebakbendera)
     router.get('/caklontong', caklontong)
     router.get('/tebaklirik', tebaklirik)
     router.get('/tebakkimia', tebakkimia)
     router.get('/family100', family100)
     router.get('/tebakkabupaten', tebakkabupaten)
     router.get('/truthdare', truthdare)
     
     // Primbon
     router.get('/artinama', artinama)
     router.get('/artimimpi', artimimpi)
     router.get('/ramaljodoh', ramaljodoh)
     router.get('/nomorhoki', nomorhoki)
     router.get('/zodiak', zodiak)
     router.get('/kecocokannama', kecocokan_nama)
     router.get('/kecocokanpasangan', kecocokan_nama_pasangan)
     router.get('/jadianpernikahan', tanggal_jadian_pernikahan)
     router.get('/sifatusaha', sifat_usaha_bisnis)
     router.get('/rejekiweton', rejeki_hoki_weton)
     router.get('/pekerjaanweton', pekerjaan_weton_lahir)
     router.get('/ramalnasib', ramalan_nasib)
     router.get('/potensipenyakit', cek_potensi_penyakit)
     router.get('/artitarot', arti_kartu_tarot)
     router.get('/haribaik', petung_hari_baik)
     router.get('/harisangar', hari_sangar_taliwangke)
     router.get('/harisial', primbon_hari_naas)
     router.get('/harinaga', rahasia_naga_hari)
     router.get('/arahrejeki', primbon_arah_rejeki)
     router.get('/peruntungan', ramalan_peruntungan)
     router.get('/wetonjawa', weton_jawa)
     router.get('/sifatkarakter', sifat_karakter_tanggal_lahir)
     router.get('/keberuntungan', potensi_keberuntungan)
     router.get('/memancingikan', primbon_memancing_ikan)
     router.get('/seberapagay', seberapagay)
     
     // Other
     router.get('/ppcouple', ppcouple)
     router.get('/wangy', wangy)
     router.get('/wangy2', wangy2)
     router.get('/nenen', nenen)
     router.get('/simp', simp)
     router.get('/sherk', sherk)
     router.get('/quotes', quotes)
     router.get('/quotesanime', quotesnime)
     router.get('/genshin', gi)
     router.get('/genshinweapon', giwp)
     router.get('/herodetail', herodetail)
     router.get('/herolist', herolist)

     // AI
     router.get('/ling26', ling26)
     router.get('/nemotron3super120b', nemotron3super120b)
     router.get('/gptoss120b', gptoss120b)
     router.get('/glm45air', glm45air)
     router.get('/nemotron3nano30b', nemotron3nano30b)
     router.get('/nemotronnano12bvl', nemotronnano12bvl)
     router.get('/qwen3coder', qwen3coder)
     router.get('/llamanemotronembedvl', llamaNemotronEmbedVl)
     
     router.use(function (req, res, next) {
        if (res.statusCode == '200') {
             res.render('notfound', {
             layout: 'notfound'
        })
     }
})

module.exports = router
